In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import statsmodels.api as sm
import statsmodels.stats as sms

In [2]:
def formatter_pvalue(x):
  return "color: red" if x < 0.05 else None

def formatter_one_zero(x):
  return "Tidak Ada" if x == 0 else "Ada"

In [4]:
df = pd.read_parquet("../dataset/curated/marts_ml_train.parquet")
df.head()

,price,kamar_tidur,kamar_mandi,kamar_pembantu,kamar_mandi_pembantu,dapur,luas_tanah,luas_bangunan,jumlah_lantai,garasi,...,facility_gas,facility_aula,facility_canopy,facility_heating,facility_musholla,facility_floorboards,facility_shed,facility_lemari_pakaian,facility_mezzanine,facility_lemari_sepatu
0,850.0,2,1,1,1,1,90.0,60.0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,563.0,2,1,0,0,1,72.0,40.0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,777.0,2,2,0,0,1,70.0,60.0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1950.0,4,3,1,1,1,200.0,170.0,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,240.0,2,1,0,0,1,90.0,45.0,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18239 entries, 0 to 18238
Data columns (total 82 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   price                     18239 non-null  float64
 1   kamar_tidur               18239 non-null  int32
 2   kamar_mandi               18239 non-null  int32
 3   kamar_pembantu            18239 non-null  int32
 4   kamar_mandi_pembantu      18239 non-null  int32
 5   dapur                     18239 non-null  int32
 6   luas_tanah                18239 non-null  float32
 7   luas_bangunan             18227 non-null  float32
 8   jumlah_lantai             18239 non-null  int32
 9   garasi                    18239 non-null  int32
 10  carport                   18239 non-null  int32
 11  lebar_jalan               18239 non-null  float32
 12  tahun_dibangun            18239 non-null  int32
 13  tahun_di_renovasi         18239 non-null  int32
 14  daya_listrik              16156 non-null  float32
 15  hadap                     6869 non-null   object
 16  sertifikat                18199 non-null  object
 17  sumber_air                12408 non-null  object
 18  pemandangan               10444 non-null  object
 19  tipe_properti             18239 non-null  object
 20  konsep_dan_gaya_rumah     9573 non-null   object
 21  kondisi_properti          16110 non-null  object
 22  kondisi_perabotan         13044 non-null  object
 23  hook                      18239 non-null  int32
 24  ruang_tamu                18239 non-null  int32
 25  ruang_makan               18239 non-null  int32
 26  terjangkau_internet       18239 non-null  int32
 27  house_mat_bata_hebel      8989 non-null   float64
 28  house_mat_bata_merah      8989 non-null   float64
 29  house_mat_beton           8989 non-null   float64
 30  house_mat_batako          8989 non-null   float64
 31  floor_mat_granit          9325 non-null   float64
 32  floor_mat_keramik         9325 non-null   float64
 33  floor_mat_ubin            9325 non-null   float64
 34  floor_mat_marmer          9325 non-null   float64
 35  floor_mat_vinyl           9325 non-null   float64
 36  tag_bisa_nego             14666 non-null  float64
 37  tag_cash_keras            14666 non-null  float64
 38  tag_komplek               14666 non-null  float64
 39  tag_perumahan             14666 non-null  float64
 40  tag_kpr                   14666 non-null  float64
 41  tag_one_gate_system       14666 non-null  float64
 42  tag_cash_bertahap         14666 non-null  float64
 43  tag_dijual_cepat          14666 non-null  float64
 44  tag_pinggir_jalan         14666 non-null  float64
 45  tag_pedesaan              14666 non-null  float64
 46  tag_masuk_gang            14666 non-null  float64
 47  facility_keamanan         14842 non-null  float64
 48  facility_ac               14842 non-null  float64
 49  facility_lapangan         14842 non-null  float64
 50  facility_taman            14842 non-null  float64
 51  facility_laundry          14842 non-null  float64
 52  facility_masjid           14842 non-null  float64
 53  facility_wastafel         14842 non-null  float64
 54  facility_one_gate_system  14842 non-null  float64
 55  facility_dapur            14842 non-null  float64
 56  facility_jalur_telepon    14842 non-null  float64
 57  facility_kolam_renang     14842 non-null  float64
 58  facility_playground       14842 non-null  float64
 59  facility_parkir           14842 non-null  float64
 60  facility_gym              14842 non-null  float64
 61  facility_water_heater     14842 non-null  float64
 62  facility_kolam_ikan       14842 non-null  float64
 63  facility_carport          14842 non-null  float64
 64  facility_air_pam          14842 non-null  float64
 65  facility_halaman          14842 non-null  float64
 66  facility_balcony          14842 non-null  float64
 67  facility_internet         14842 non-null  float64
 68  facility_air_tanah        14842 non-null  float64
 69  facility_dishwasher       14842 non-null  float64
 70  facility_water_tank       14842 non-null  float64
 71  facility_garasi           14842 non-null  float64
 72  facility_gas              14842 non-null  float64
 73  facility_aula             14842 non-null  float64
 74  facility_canopy           14842 non-null  float64
 75  facility_heating          14842 non-null  float64
 76  facility_musholla         14842 non-null  float64
 77  facility_floorboards      14842 non-null  float64
 78  facility_shed             14842 non-null  float64
 79  facility_lemari_pakaian   14842 non-null  float64
 80  facility_mezzanine        14842 non-null  float64
 81  facility_lemari_sepatu    14842 non-null  float64
dtypes: float32(4), float64(56), int32(14), object(8)
memory usage: 10.2+ MB